deployments:
  DefaultApp:
        filename:
          ./Dockerfile
        port_forwarding:
          80:3000
  Ruby260App:
        filename:
          ./Dockerfile-260
        port_forwarding:
          80:3000
